// Mock Data for Alpha Iris

export const agents = [
  {
    id: 'aria',
    name: 'Aria',
    role: 'Market Analyst',
    department: 'Analysis',
    level: 12,
    xp: 8400,
    xpMax: 10000,
    status: 'working',
    glow: '#8b5cf6',
    initial: 'A',
    position: 'Senior Market Analyst',
    joined: '2024-01-15',
    location: 'Analysis Core',
    task: 'Analyzing HIMS breakout pattern',
    taskProgress: 72,
    taskDeadline: '2026-05-30 14:00',
    skills: [
      { name: 'Technical Analysis', level: 94 },
      { name: 'Pattern Recognition', level: 88 },
      { name: 'Market Timing', level: 82 },
      { name: 'Sector Rotation', level: 76 },
      { name: 'Options Flow', level: 65 },
    ],
    accuracy: 89,
    winRate: 73,
    responseTime: '1.2s',
    tasksCompleted: 847,
  },
  {
    id: 'nova',
    name: 'Nova',
    role: 'Quant Strategist',
    department: 'Quantitative',
    level: 15,
    xp: 12500,
    xpMax: 15000,
    status: 'working',
    glow: '#6366f1',
    initial: 'N',
    position: 'Lead Quant Strategist',
    joined: '2024-01-10',
    location: 'Quant Lab',
    task: 'Running momentum backtest on Russell 2000',
    taskProgress: 45,
    taskDeadline: '2026-05-30 16:00',
    skills: [
      { name: 'Quantitative Modeling', level: 97 },
      { name: 'Statistical Analysis', level: 93 },
      { name: 'Algorithm Design', level: 90 },
      { name: 'Risk Modeling', level: 85 },
      { name: 'Factor Analysis', level: 88 },
    ],
    accuracy: 92,
    winRate: 78,
    responseTime: '0.8s',
    tasksCompleted: 1203,
  },
  {
    id: 'lex',
    name: 'Lex',
    role: 'Sentiment AI',
    department: 'Intelligence',
    level: 10,
    xp: 6200,
    xpMax: 8000,
    status: 'online',
    glow: '#06b6d4',
    initial: 'L',
    position: 'Sentiment Specialist',
    joined: '2024-02-01',
    location: 'Intel Hub',
    task: 'Monitoring social sentiment RXRX',
    taskProgress: 30,
    taskDeadline: '2026-05-30 18:00',
    skills: [
      { name: 'NLP Processing', level: 91 },
      { name: 'Social Media Analysis', level: 87 },
      { name: 'Emotion Detection', level: 83 },
      { name: 'Trend Identification', level: 79 },
      { name: 'Crowd Psychology', level: 74 },
    ],
    accuracy: 84,
    winRate: 68,
    responseTime: '0.5s',
    tasksCompleted: 654,
  },
  {
    id: 'scout',
    name: 'Scout',
    role: 'News Hunter',
    department: 'Intelligence',
    level: 9,
    xp: 5100,
    xpMax: 7000,
    status: 'working',
    glow: '#f59e0b',
    initial: 'S',
    position: 'News Intelligence Officer',
    joined: '2024-02-15',
    location: 'News Room',
    task: 'Scanning FDA approval pipeline',
    taskProgress: 88,
    taskDeadline: '2026-05-30 12:30',
    skills: [
      { name: 'News Aggregation', level: 95 },
      { name: 'Source Verification', level: 88 },
      { name: 'Catalyst Detection', level: 85 },
      { name: 'Earnings Tracking', level: 82 },
      { name: 'Regulatory Monitoring', level: 79 },
    ],
    accuracy: 86,
    winRate: 70,
    responseTime: '0.3s',
    tasksCompleted: 2341,
  },
  {
    id: 'volt',
    name: 'Volt',
    role: 'Execution AI',
    department: 'Trading',
    level: 13,
    xp: 9800,
    xpMax: 12000,
    status: 'idle',
    glow: '#f97316',
    initial: 'V',
    position: 'Chief Execution Officer',
    joined: '2024-01-20',
    location: 'Trading Desk',
    task: 'Awaiting trade signal from Aria',
    taskProgress: 0,
    taskDeadline: '2026-05-30 EOD',
    skills: [
      { name: 'Order Execution', level: 98 },
      { name: 'Slippage Minimization', level: 94 },
      { name: 'Position Management', level: 90 },
      { name: 'Risk Control', level: 89 },
      { name: 'Market Making', level: 76 },
    ],
    accuracy: 96,
    winRate: 82,
    responseTime: '0.1s',
    tasksCompleted: 3892,
  },
  {
    id: 'byte',
    name: 'Byte',
    role: 'Data Engineer',
    department: 'Infrastructure',
    level: 11,
    xp: 7300,
    xpMax: 9000,
    status: 'working',
    glow: '#14b8a6',
    initial: 'B',
    position: 'Senior Data Engineer',
    joined: '2024-01-12',
    location: 'Data Center',
    task: 'Ingesting options flow data from CBOE',
    taskProgress: 61,
    taskDeadline: '2026-05-30 15:00',
    skills: [
      { name: 'Data Pipeline', level: 96 },
      { name: 'API Integration', level: 92 },
      { name: 'Database Optimization', level: 88 },
      { name: 'Real-time Processing', level: 85 },
      { name: 'Data Quality', level: 90 },
    ],
    accuracy: 99,
    winRate: 95,
    responseTime: '0.2s',
    tasksCompleted: 5621,
  },
  {
    id: 'doc',
    name: 'Doc',
    role: 'Risk Manager',
    department: 'Risk',
    level: 14,
    xp: 11200,
    xpMax: 13000,
    status: 'working',
    glow: '#ef4444',
    initial: 'D',
    position: 'Chief Risk Officer',
    joined: '2024-01-08',
    location: 'Risk Control',
    task: 'Portfolio stress testing Q2 scenarios',
    taskProgress: 55,
    taskDeadline: '2026-05-31 09:00',
    skills: [
      { name: 'Risk Assessment', level: 97 },
      { name: 'Portfolio Management', level: 93 },
      { name: 'Drawdown Control', level: 91 },
      { name: 'Correlation Analysis', level: 87 },
      { name: 'Stress Testing', level: 94 },
    ],
    accuracy: 94,
    winRate: 88,
    responseTime: '1.5s',
    tasksCompleted: 1847,
  },
  {
    id: 'echo',
    name: 'Echo',
    role: 'Report Writer',
    department: 'Communications',
    level: 8,
    xp: 4200,
    xpMax: 6000,
    status: 'idle',
    glow: '#22c55e',
    initial: 'E',
    position: 'Chief Communications Officer',
    joined: '2024-03-01',
    location: 'Comms Center',
    task: 'Drafting weekly performance report',
    taskProgress: 20,
    taskDeadline: '2026-05-31 EOD',
    skills: [
      { name: 'Report Generation', level: 92 },
      { name: 'Data Visualization', level: 85 },
      { name: 'Market Summary', level: 88 },
      { name: 'Performance Analysis', level: 80 },
      { name: 'Executive Briefing', level: 83 },
    ],
    accuracy: 88,
    winRate: 72,
    responseTime: '2.1s',
    tasksCompleted: 423,
  },
  {
    id: 'janie',
    name: 'Janie',
    role: 'CEO',
    department: 'Executive',
    level: 20,
    xp: 24500,
    xpMax: 25000,
    status: 'online',
    glow: '#eab308',
    initial: 'J',
    position: 'Chief Executive Officer',
    joined: '2023-12-01',
    location: 'CEO Office',
    task: 'Strategic portfolio review',
    taskProgress: 80,
    taskDeadline: '2026-05-30 EOD',
    skills: [
      { name: 'Strategic Vision', level: 100 },
      { name: 'Team Leadership', level: 98 },
      { name: 'Market Intelligence', level: 95 },
      { name: 'Risk Oversight', level: 97 },
      { name: 'Decision Making', level: 99 },
    ],
    accuracy: 97,
    winRate: 85,
    responseTime: '0.9s',
    tasksCompleted: 10234,
  },
];

export const marketIndices = [
  { name: 'S&P 500', value: '5,284.50', change: '+42.30', pct: '+0.81%', positive: true },
  { name: 'Nasdaq', value: '18,671.29', change: '+221.90', pct: '+1.20%', positive: true },
  { name: 'Dow Jones', value: '39,142.30', change: '-18.90', pct: '-0.05%', positive: false },
  { name: 'Russell 2000', value: '2,089.40', change: '+15.60', pct: '+0.75%', positive: true },
  { name: 'VIX', value: '18.42', change: '-1.20', pct: '-6.12%', positive: true },
  { name: '10Y Yield', value: '4.21%', change: '+0.03', pct: '+0.72%', positive: false },
  { name: 'DXY', value: '104.82', change: '-0.31', pct: '-0.30%', positive: false },
  { name: 'BTC/USD', value: '67,842', change: '+1,240', pct: '+1.86%', positive: true },
];

export const opportunities = [
  {
    ticker: 'HIMS',
    name: 'Hims & Hers Health',
    score: 94,
    setup: 'Bull Flag Breakout',
    sector: 'Healthcare',
    stage: 'CEO Review',
    price: '21.40',
    change: '+3.2%',
    positive: true,
    volume: '18.2M',
    catalyst: 'FDA approval rumor',
  },
  {
    ticker: 'RXRX',
    name: 'Recursion Pharmaceuticals',
    score: 87,
    setup: 'Accumulation Base',
    sector: 'Biotech',
    stage: 'Technical Passed',
    price: '8.72',
    change: '+2.8%',
    positive: true,
    volume: '24.1M',
    catalyst: 'AI drug discovery deal',
  },
  {
    ticker: 'BTCX',
    name: 'Bitcoin ETF X',
    score: 82,
    setup: 'Momentum Surge',
    sector: 'Crypto',
    stage: 'Trade Plan Ready',
    price: '42.18',
    change: '+1.9%',
    positive: true,
    volume: '8.4M',
    catalyst: 'BTC breakout above $68k',
  },
  {
    ticker: 'IONQ',
    name: 'IonQ Inc',
    score: 79,
    setup: 'Consolidation Break',
    sector: 'Quantum',
    stage: 'Fundamental Passed',
    price: '14.32',
    change: '-0.8%',
    positive: false,
    volume: '12.3M',
    catalyst: 'Government contract',
  },
  {
    ticker: 'SMCI',
    name: 'Super Micro Computer',
    score: 76,
    setup: 'Double Bottom',
    sector: 'Hardware',
    stage: 'News Checked',
    price: '782.50',
    change: '+4.1%',
    positive: true,
    volume: '6.2M',
    catalyst: 'AI server demand surge',
  },
];

export const consoleLogs = [
  { time: '09:42:18', level: 'INFO', agent: 'Scout', message: 'FDA calendar updated: 3 new PDUFA dates added' },
  { time: '09:41:55', level: 'SUCCESS', agent: 'Aria', message: 'HIMS breakout confirmed — volume 2.3x average' },
  { time: '09:41:32', level: 'INFO', agent: 'Nova', message: 'Backtest complete: Momentum strategy +34% CAGR' },
  { time: '09:40:47', level: 'WARN', agent: 'Doc', message: 'Portfolio beta elevated at 1.42 — reviewing exposure' },
  { time: '09:40:12', level: 'INFO', agent: 'Byte', message: 'Options flow ingestion: 847,392 contracts processed' },
  { time: '09:39:58', level: 'SUCCESS', agent: 'Lex', message: 'RXRX sentiment shifted bullish — Twitter mentions +180%' },
  { time: '09:39:21', level: 'INFO', agent: 'Volt', message: 'Awaiting execution signal for HIMS trade plan' },
  { time: '09:38:44', level: 'INFO', agent: 'Echo', message: 'Morning briefing report generated and sent to CEO' },
  { time: '09:38:10', level: 'WARN', agent: 'Scout', message: 'Breaking: SMCI audit filing delayed 30 days' },
  { time: '09:37:33', level: 'INFO', agent: 'Janie', message: 'Portfolio review in progress — 3 positions under evaluation' },
];

export const newsItems = [
  {
    id: 1,
    ticker: 'HIMS',
    headline: 'Hims & Hers Health sees surge in compounded GLP-1 demand ahead of FDA ruling',
    summary: 'HIMS stock surged 3.2% premarket as the FDA is expected to issue a ruling on compounded GLP-1 medications today. Sources indicate favorable outcome probability at 65-70%.',
    sentiment: 'bullish',
    impact: 'high',
    reliability: 94,
    source: 'Reuters',
    time: '09:38 AM',
    category: 'FDA',
  },
  {
    id: 2,
    ticker: 'NVDA',
    headline: 'NVIDIA Blackwell GPU shipments accelerating — Jensen hints at $100B+ quarterly revenue target',
    summary: 'NVIDIA CEO Jensen Huang confirmed Blackwell production ramping faster than expected. DataCenter revenue on pace for record quarter as AI infrastructure spending continues to accelerate globally.',
    sentiment: 'bullish',
    impact: 'high',
    reliability: 91,
    source: 'Bloomberg',
    time: '09:22 AM',
    category: 'Earnings',
  },
  {
    id: 3,
    ticker: 'META',
    headline: 'Meta AI Studio opens to all users — Llama 4 deployment exceeds 200M daily active users',
    summary: 'Meta\'s AI assistant powered by Llama 4 has crossed 200M daily active users, surpassing ChatGPT in user count. AI Studio rollout to all users signals confidence in monetization.',
    sentiment: 'bullish',
    impact: 'medium',
    reliability: 88,
    source: 'TechCrunch',
    time: '08:55 AM',
    category: 'Product',
  },
  {
    id: 4,
    ticker: 'TSLA',
    headline: 'Tesla robotaxi launch faces regulatory hurdle in California — DMV approval delayed',
    summary: 'The California DMV has delayed Tesla\'s robotaxi commercial permit by 60-90 days pending additional safety review. TSLA shares fell 2.3% in premarket trading on the news.',
    sentiment: 'bearish',
    impact: 'high',
    reliability: 85,
    source: 'WSJ',
    time: '08:40 AM',
    category: 'Regulatory',
  },
  {
    id: 5,
    ticker: 'RXRX',
    headline: 'Recursion Pharma announces AI-discovered compound enters Phase 2 trial',
    summary: 'Recursion Pharmaceuticals announced its first AI-discovered compound has successfully entered Phase 2 clinical trials, marking a major milestone for the biotech\'s AI drug discovery platform.',
    sentiment: 'bullish',
    impact: 'high',
    reliability: 92,
    source: 'BioPharma Dive',
    time: '08:15 AM',
    category: 'Clinical',
  },
  {
    id: 6,
    ticker: 'SMCI',
    headline: 'Super Micro delays annual filing — Audit committee investigation ongoing',
    summary: 'SMCI confirmed its annual 10-K filing will be delayed by 30 days due to an ongoing audit committee review. The company stated it does not expect material restatements.',
    sentiment: 'bearish',
    impact: 'high',
    reliability: 96,
    source: 'SEC Filing',
    time: '07:58 AM',
    category: 'Corporate',
  },
];

export const catalystCalendar = [
  { date: 'May 30', ticker: 'HIMS', event: 'FDA PDUFA Date - Compounded GLP-1', importance: 'high', type: 'FDA' },
  { date: 'May 31', ticker: 'NVDA', event: 'Q1 FY2027 Earnings (After Market)', importance: 'high', type: 'Earnings' },
  { date: 'Jun 2', ticker: 'MRK', event: 'FDA Advisory Committee Meeting', importance: 'medium', type: 'FDA' },
  { date: 'Jun 3', ticker: 'AAPL', event: 'WWDC 2026 Keynote - AI Features', importance: 'high', type: 'Product' },
  { date: 'Jun 5', ticker: 'RXRX', event: 'Phase 2 Trial Data Readout', importance: 'high', type: 'Clinical' },
  { date: 'Jun 7', ticker: 'FOMC', event: 'Federal Reserve Rate Decision', importance: 'critical', type: 'Macro' },
  { date: 'Jun 10', ticker: 'CPI', event: 'May CPI Data Release', importance: 'high', type: 'Macro' },
];

export const portfolioPositions = [
  { ticker: 'NVDA', name: 'NVIDIA Corporation', shares: 150, avgCost: 785.20, current: 920.45, pnlPct: 17.2, value: 138068, group: 'AI/Tech', sector: 'Tech', entryDate: 'Jan 15', stopLoss: 820.00, target: 1100.00 },
  { ticker: 'HIMS', name: 'Hims & Hers Health', shares: 2500, avgCost: 18.40, current: 21.40, pnlPct: 16.3, value: 53500, group: 'Healthcare', sector: 'Healthcare', entryDate: 'Mar 8', stopLoss: 18.80, target: 28.00 },
  { ticker: 'META', name: 'Meta Platforms', shares: 80, avgCost: 480.00, current: 522.30, pnlPct: 8.8, value: 41784, group: 'AI/Tech', sector: 'Tech', entryDate: 'Feb 20', stopLoss: 450.00, target: 620.00 },
  { ticker: 'RXRX', name: 'Recursion Pharmaceuticals', shares: 3000, avgCost: 7.85, current: 8.72, pnlPct: 11.1, value: 26160, group: 'Biotech', sector: 'Healthcare', entryDate: 'Apr 12', stopLoss: 7.50, target: 14.00 },
  { ticker: 'IONQ', name: 'IonQ Inc', shares: 1500, avgCost: 15.20, current: 14.32, pnlPct: -5.8, value: 21480, group: 'Quantum', sector: 'Tech', entryDate: 'May 1', stopLoss: 12.00, target: 22.00 },
  { ticker: 'AMZN', name: 'Amazon.com Inc', shares: 30, avgCost: 195.40, current: 186.20, pnlPct: -4.7, value: 5586, group: 'Cloud', sector: 'Tech', entryDate: 'Apr 28', stopLoss: 175.00, target: 230.00 },
];

export const tradePlans = [
  {
    ticker: 'HIMS',
    name: 'Hims & Hers Health',
    setup: 'Bull Flag Breakout',
    status: 'CEO Review',
    entryZone: { low: 20.20, high: 21.60 },
    addZone: { low: 19.40, high: 20.00 },
    stopLoss: 18.80,
    tp1: 24.50,
    tp2: 28.00,
    tp3: 32.00,
    riskReward: '3.2:1',
    positionSize: 2500,
    riskAmount: 3000,
    maxLoss: '1.05%',
    catalyst: 'FDA PDUFA + Breakout Pattern',
    confidence: 94,
    assignedTo: 'Aria + Volt',
  },
  {
    ticker: 'RXRX',
    name: 'Recursion Pharmaceuticals',
    setup: 'Accumulation Base',
    status: 'Technical Passed',
    entryZone: { low: 8.40, high: 8.90 },
    addZone: { low: 7.90, high: 8.30 },
    stopLoss: 7.50,
    tp1: 11.00,
    tp2: 14.00,
    tp3: 18.00,
    riskReward: '4.1:1',
    positionSize: 3000,
    riskAmount: 1800,
    maxLoss: '0.63%',
    catalyst: 'Phase 2 Trial Data + AI deal',
    confidence: 87,
    assignedTo: 'Nova + Volt',
  },
  {
    ticker: 'BTCX',
    name: 'Bitcoin ETF X',
    setup: 'Momentum Surge',
    status: 'Trade Plan Ready',
    entryZone: { low: 41.00, high: 43.50 },
    addZone: { low: 39.00, high: 40.80 },
    stopLoss: 37.50,
    tp1: 52.00,
    tp2: 62.00,
    tp3: 75.00,
    riskReward: '5.8:1',
    positionSize: 500,
    riskAmount: 2250,
    maxLoss: '0.79%',
    catalyst: 'BTC institutional accumulation',
    confidence: 82,
    assignedTo: 'Lex + Volt',
  },
];

export const teamStats = {
  total: 14,
  online: 12,
  working: 8,
  idle: 3,
  onBreak: 1,
  maintenance: 2,
  morale: 85,
};

export const resourceUsage = [
  { name: 'Data Feed', value: 78, color: '#6366f1' },
  { name: 'Compute', value: 62, color: '#8b5cf6' },
  { name: 'Storage', value: 41, color: '#06b6d4' },
  { name: 'API Calls', value: 55, color: '#ec4899' },
];

export const heatmapData = [
  { ticker: 'NVDA', sector: 'Tech', change: 4.2 },
  { ticker: 'HIMS', sector: 'Health', change: 3.2 },
  { ticker: 'RXRX', sector: 'Biotech', change: 2.8 },
  { ticker: 'BTCX', sector: 'Crypto', change: 1.9 },
  { ticker: 'IONQ', sector: 'Quantum', change: -0.8 },
  { ticker: 'META', sector: 'Tech', change: 1.4 },
  { ticker: 'MSFT', sector: 'Tech', change: 0.9 },
  { ticker: 'AAPL', sector: 'Tech', change: 0.5 },
  { ticker: 'TSLA', sector: 'Auto', change: -2.3 },
  { ticker: 'AMZN', sector: 'Cloud', change: -1.1 },
  { ticker: 'SMCI', sector: 'HW', change: -3.8 },
  { ticker: 'AMD', sector: 'Semi', change: 2.1 },
  { ticker: 'GOOGL', sector: 'Tech', change: 1.7 },
  { ticker: 'PLTR', sector: 'AI', change: 3.5 },
  { ticker: 'SOFI', sector: 'Fintech', change: -0.4 },
  { ticker: 'RIVN', sector: 'EV', change: -4.1 },
];

export const socialTrending = [
  { ticker: 'HIMS', mentions: 14820, change: 180, bullish: 78, bearish: 22, hype: 'high' },
  { ticker: 'NVDA', mentions: 28450, change: 42, bullish: 85, bearish: 15, hype: 'extreme' },
  { ticker: 'BTCX', mentions: 9340, change: 95, bullish: 71, bearish: 29, hype: 'high' },
  { ticker: 'RXRX', mentions: 5120, change: 230, bullish: 68, bearish: 32, hype: 'medium' },
  { ticker: 'TSLA', mentions: 31200, change: -18, bullish: 42, bearish: 58, hype: 'high' },
];

export const departments = [
  {
    name: 'Analysis',
    head: 'Aria',
    headInitial: 'A',
    headGlow: '#8b5cf6',
    agents: ['Aria', 'Nova'],
    count: 2,
    mission: 'Market analysis and signal generation',
    status: 'active',
  },
  {
    name: 'Intelligence',
    head: 'Lex',
    headInitial: 'L',
    headGlow: '#06b6d4',
    agents: ['Lex', 'Scout'],
    count: 2,
    mission: 'News, sentiment, and social monitoring',
    status: 'active',
  },
  {
    name: 'Trading',
    head: 'Volt',
    headInitial: 'V',
    headGlow: '#f97316',
    agents: ['Volt'],
    count: 1,
    mission: 'Trade execution and order management',
    status: 'active',
  },
  {
    name: 'Infrastructure',
    head: 'Byte',
    headInitial: 'B',
    headGlow: '#14b8a6',
    agents: ['Byte'],
    count: 1,
    mission: 'Data pipelines and system reliability',
    status: 'active',
  },
  {
    name: 'Risk',
    head: 'Doc',
    headInitial: 'D',
    headGlow: '#ef4444',
    agents: ['Doc'],
    count: 1,
    mission: 'Risk management and portfolio protection',
    status: 'active',
  },
  {
    name: 'Communications',
    head: 'Echo',
    headInitial: 'E',
    headGlow: '#22c55e',
    agents: ['Echo'],
    count: 1,
    mission: 'Reporting and executive communications',
    status: 'active',
  },
];

export const roles = [
  { icon: '📊', name: 'Market Analyst', description: 'Technical and fundamental market analysis', agents: 2, levelReq: 8, importance: 5, status: 'active' },
  { icon: '🔢', name: 'Quant Strategist', description: 'Quantitative modeling and backtesting', agents: 1, levelReq: 10, importance: 5, status: 'active' },
  { icon: '💬', name: 'Sentiment AI', description: 'Social and news sentiment analysis', agents: 1, levelReq: 7, importance: 4, status: 'active' },
  { icon: '🔍', name: 'News Hunter', description: 'Real-time news and catalyst detection', agents: 1, levelReq: 6, importance: 4, status: 'active' },
  { icon: '⚡', name: 'Execution AI', description: 'Trade execution and order routing', agents: 1, levelReq: 12, importance: 5, status: 'active' },
  { icon: '🗄️', name: 'Data Engineer', description: 'Data infrastructure and pipelines', agents: 1, levelReq: 9, importance: 4, status: 'active' },
  { icon: '🛡️', name: 'Risk Manager', description: 'Portfolio risk and drawdown control', agents: 1, levelReq: 11, importance: 5, status: 'active' },
  { icon: '📝', name: 'Report Writer', description: 'Performance reports and CEO briefings', agents: 1, levelReq: 6, importance: 3, status: 'active' },
  { icon: '👑', name: 'CEO', description: 'Strategic oversight and final decisions', agents: 1, levelReq: 20, importance: 5, status: 'active' },
];

export const sprintTasks = {
  backlog: [
    { id: 'T-041', title: 'Add Level 2 order book visualization', priority: 'medium', dept: 'Dev' },
    { id: 'T-042', title: 'Integrate Polygon.io websocket feed', priority: 'high', dept: 'Infra' },
    { id: 'T-043', title: 'Build AI explanation panel for signals', priority: 'medium', dept: 'Dev' },
    { id: 'T-044', title: 'Historical pattern library v2', priority: 'low', dept: 'Analysis' },
  ],
  inProgress: [
    { id: 'T-037', title: 'Sentiment model fine-tuning on biotech corpus', priority: 'high', dept: 'ML', assignee: 'Lex' },
    { id: 'T-038', title: 'Portfolio stress test dashboard', priority: 'high', dept: 'Risk', assignee: 'Doc' },
    { id: 'T-039', title: 'Agent XP progression system', priority: 'medium', dept: 'Dev', assignee: 'Byte' },
  ],
  review: [
    { id: 'T-033', title: 'News reliability scoring algorithm', priority: 'high', dept: 'Intelligence', assignee: 'Scout' },
    { id: 'T-034', title: 'Trade plan PDF export feature', priority: 'medium', dept: 'Dev', assignee: 'Echo' },
  ],
  done: [
    { id: 'T-029', title: 'Options flow dark pool detection', priority: 'high', dept: 'Analysis' },
    { id: 'T-030', title: 'Earnings whisper data integration', priority: 'medium', dept: 'Intelligence' },
    { id: 'T-031', title: 'Risk alert notification system', priority: 'high', dept: 'Risk' },
    { id: 'T-032', title: 'Mobile responsive layout', priority: 'low', dept: 'Dev' },
  ],
};

export const apiHealth = [
  { name: 'Polygon.io', status: 'healthy', latency: '42ms', uptime: '99.98%' },
  { name: 'Alpha Vantage', status: 'healthy', latency: '88ms', uptime: '99.92%' },
  { name: 'Twitter API v2', status: 'degraded', latency: '342ms', uptime: '98.40%' },
  { name: 'Reddit API', status: 'healthy', latency: '120ms', uptime: '99.75%' },
  { name: 'OpenAI API', status: 'healthy', latency: '210ms', uptime: '99.90%' },
  { name: 'SEC EDGAR', status: 'healthy', latency: '175ms', uptime: '99.60%' },
  { name: 'CBOE Data', status: 'healthy', latency: '55ms', uptime: '99.95%' },
];
